### PR TITLE
REPL: decouple and fix

### LINKED ISSUE #683: REPL cannot use literal patterns
image

### PR DESCRIPTION
**Pull request by imkiva**
and highlight keywords using colors from configured color scheme...
and fix #683

### CODE REVIEW

File: tools-repl/src/main/java/org/aya/repl/ReplLexer.java [hunk 1]
```diff
@@ -0,0 +1,17 @@
+// Copyright (c) 2020-2022 Tesla (Yinsen) Zhang.
+// Use of this source code is governed by the MIT license that can be found in the LICENSE.md file.
+package org.aya.repl;
+
+import kala.collection.immutable.ImmutableSeq;
+import org.jetbrains.annotations.NotNull;
+
+public interface ReplLexer<T> {
```
Comment (ice1000) [inline tools-repl/src/main/java/org/aya/repl/ReplLexer.java:8]: `extends FlexLexer`?

Comment (ice1000) [reply tools-repl/src/main/java/org/aya/repl/ReplLexer.java:8]: I see. My bad.

**Review by ice1000 — APPROVED** [review]
bors r+
