### PR TITLE
Kiva fixing something today

### LINKED ISSUE #694: Kiva fixing something tomorrow
Then it should be stored in RenderOptions itself.

I am fixing it tomorrow.

_Originally posted by @imkiva in https://github.com/aya-prover/aya-dev/pull/693#discussion_r1026696499_

### PR DESCRIPTION
**Pull request by imkiva**
fix #694

- Memorize `stylist` for each output target
- Strongly typed argument for `:color` and `:style`, as well as completions!

### CODE REVIEW

**Comment by imkiva** [comment]
The 700th!

image

File: cli/src/main/java/org/aya/cli/render/RenderOptions.java [hunk 1]
```diff
@@ -83,13 +119,15 @@ public boolean isDefault() {
...
-      case HTML -> new Html5Stylist(buildColorScheme(), buildStyleFamily());
-      case Plain -> new DebugStylist(buildColorScheme(), buildStyleFamily());
-    };
+    return stylistCaches.getOrPut(output, () -> Try.of(() -> {
+      if (isDefault()) return defaultStylist(output);
+      return switch (output) {
+        case Terminal -> new UnixTermStylist(buildColorScheme(), buildStyleFamily());
+        case LaTeX -> new TeXStylist(buildColorScheme(), buildStyleFamily());
+        case HTML -> new Html5Stylist(buildColorScheme(), buildStyleFamily());
+        case Plain -> new DebugStylist(buildColorScheme(), buildStyleFamily());
```
Comment (HoshinoTented) [inline cli/src/main/java/org/aya/cli/render/RenderOptions.java:128]: It seems to build the same color scheme again when we require the stylist of another `OutputTarget`.

Comment (imkiva) [reply cli/src/main/java/org/aya/cli/render/RenderOptions.java]: Tql

File: cli/src/main/java/org/aya/cli/render/RenderOptions.java [hunk 2]
```diff
@@ -73,6 +77,38 @@ public boolean isDefault() {
...
+
+  public void updateStyleFamily(@NotNull Either<StyleFamilyName, Path> nameOrPath) throws IllegalArgumentException {
+    if (nameOrPath.isRight()) throw new IllegalArgumentException("We don't support custom style family yet :)");
+    this.styleFamily = nameOrPath.getLeftValue();
+    invalidate();
+  }
+
+  public void invalidate() {
+    colorSchemeCache = null;
+    styleFamilyCache = null;
```
Comment (HoshinoTented) [inline cli/src/main/java/org/aya/cli/render/RenderOptions.java:109]: Maybe we should invalidate them separately? However, this is okay for now because we can only change the color scheme.

**Review by HoshinoTented — APPROVED** [review]
LGTM!!

File: cli/src/main/java/org/aya/cli/render/RenderOptions.java (hunk 2 above)
Comment (imkiva) [reply cli/src/main/java/org/aya/cli/render/RenderOptions.java:109]: I don't think it is a good idea, as it makes the status of render options much more complicated.

Comment (imkiva) [reply cli/src/main/java/org/aya/cli/render/RenderOptions.java:109]: And we don't care about the extra performance overhead. It must not be the bottleneck.

**Comment by imkiva** [comment]
bors merge

File: cli/src/main/java/org/aya/cli/render/RenderOptions.java (hunk 2 above)
Comment (HoshinoTented) [reply cli/src/main/java/org/aya/cli/render/RenderOptions.java:109]: You persuaded me.
