### PR TITLE
Fix #972

### LINKED ISSUE #972: InternalException about Generalized Variables
image

### PR DESCRIPTION
**Pull request by HoshinoTented**
This PR fixes #972 by:
- [x] appending generalized variables after body resolving
- [x] luck

### CODE REVIEW

File: base/src/test/java/org/aya/test/LibraryTest.java [hunk 1]
```diff
@@ -32,15 +34,23 @@
...
-    FileUtil.deleteRecursively(DIR.resolve("build").resolve("out"));
-    assertEquals(0, compile());
+    FileUtil.deleteRecursively(libRoot.resolve("build").resolve("out"));
+    assertEquals(0, compile(libRoot));
     // The third time should do nothing.
-    assertEquals(0, compile());
+    assertEquals(0, compile(libRoot));
+  }
+
+  @Test public void fastTestOnDisk() throws IOException {
```
Comment (HoshinoTented) [inline base/src/test/java/org/aya/test/LibraryTest.java:52]: manual test only :(

Comment (ice1000) [reply base/src/test/java/org/aya/test/LibraryTest.java:52]: What do you mean? CI says it already passes tes
